const fs = require("fs");
const path = require("path");

async function generateReport(format = "md") {
  const reportPath = path.join(process.cwd(), ".guardrail-report.json");

  let data;
  try {
    data = JSON.parse(fs.readFileSync(reportPath, "utf-8"));
  } catch {
    return "# GuardRail Report\n\nNo scan data found. Run `guardrail scan` first.\n";
  }

  if (format === "md" || format === "markdown") {
    return generateMarkdown(data);
  }
  if (format === "html") {
    return generateHtml(data);
  }
  return JSON.stringify(data, null, 2);
}

function generateMarkdown(data) {
  const { issues, summary, targetPath, scannedAt } = data;
  let md = "";

  md += `# 🛡️ GuardRail Security Report\n\n`;
  md += `- **Target**: \`${targetPath}\`\n`;
  md += `- **Scanned**: ${new Date(scannedAt).toISOString()}\n`;
  md += `- **Score**: **${summary.score}/100** (Grade: **${summary.grade}**)\n\n`;

  md += `## Summary\n\n`;
  md += `| Severity | Count |\n`;
  md += `|----------|-------|\n`;
  md += `| 🔴 Critical | ${summary.critical} |\n`;
  md += `| 🟠 High | ${summary.high} |\n`;
  md += `| 🟡 Medium | ${summary.medium} |\n`;
  md += `| 🔵 Low | ${summary.low} |\n`;
  md += `| **Total** | **${summary.total}** |\n\n`;

  if (issues.secrets.length > 0) {
    md += `## 🔑 Secrets & Credentials (${issues.secrets.length})\n\n`;
    for (const item of issues.secrets.slice(0, 20)) {
      md += `- **${item.severity.toUpperCase()}** — \`${item.file}:${item.line}\` — ${item.message}\n`;
    }
    md += "\n";
  }

  if (issues.dependencies.length > 0) {
    md += `## 📦 Dependencies (${issues.dependencies.length})\n\n`;
    for (const item of issues.dependencies.slice(0, 20)) {
      md += `- **${item.severity.toUpperCase()}** — \`${item.package}@${item.version}\` — ${item.message}\n`;
    }
    md += "\n";
  }

  if (issues.owasp.length > 0) {
    md += `## 🐛 Code Vulnerabilities (${issues.owasp.length})\n\n`;
    for (const item of issues.owasp.slice(0, 20)) {
      md += `- **${item.severity.toUpperCase()}** — \`${item.file}:${item.line}\` — ${item.message}\n`;
    }
    md += "\n";
  }

  if (issues.config.length > 0) {
    md += `## ⚙️ Configuration Issues (${issues.config.length})\n\n`;
    for (const item of issues.config.slice(0, 20)) {
      md += `- **${item.severity.toUpperCase()}** — \`${item.file}:${item.line}\` — ${item.message}\n`;
    }
    md += "\n";
  }

  md += `---\n*Generated by [GuardRail](https://github.com/xiaohou2503687-design/guardrail)*\n`;

  return md;
}

function generateHtml(data) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>GuardRail Report</title></head><body><pre>${generateMarkdown(data)}</pre></body></html>`;
}

module.exports = { generateReport };
